[build]
  base = "amr-ui"          # Netlify runs from /amr-ui
  command = "npm run build"
  publish = "dist"         # <-- relative to amr-ui

[build.environment]
  NODE_VERSION = "20"

# SPA fallback so React Router works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
