[build]
  base = "amr-ui"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE = "https://amr-app.onrender.com"
  VITE_API_TOKEN = "feb91ba9962758d186f6d011ed93bee659998aa8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
